
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wowapptest
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: email ID
    password: password
    properties:
      mail:
         smtp:
           auth: true
           starttls:
             enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



